### ISSUE TITLE
Enhancement - R wrapper for the Domo Java CLI

### ISSUE THREAD

**Issue by jimmyg3g** [domoinc/rdomo#2]
This is great! Any plans for an official domoinc R wrapper for the Domo Java CLI? Here are a few functions: https://github.com/jimmyg3g/domoclir.

**Comment by jeremydmorris** [comment]
I took a quick look at the functions in your package and I think there's a good amount of overlap between the two. The data set functionality is all here: listing data sets (ds_list), creating data sets (ds_create), updating data sets (ds_update), updating data set schemas (also ds_update), retrieving schemas and other data set meta data (ds_meta). This package covers most of the functionality available in the [public API](https://developer.domo.com/docs/api-overview/api-overview), so some of the functions you have that rely on more internal APIs won't be available (until it is included in the public APIs, that is). That would include the dataflow manipulation I saw in there and the ability to interact with cards. Thanks for the note and please submit any feedback here or w/in Domo itself. Also, feel free to make adjustments yourself and submit them for review.
